const CONSTANTS = {
  fallbackManga: {
    comics: [
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/hau-cung-cua-nu-de-mua-2.jpg",
        title: "Hậu Cung Của Nữ Đế - Mùa 2",
        id: "hau-cung-cua-nu-de-mua-2",
        is_trending: false,
        short_description: "",
        last_chapters: [
          { id: 89, name: "Chapter 90", updated_at: "44 phút trước" },
          { id: 88, name: "Chapter 89", updated_at: "44 phút trước" },
          { id: 87, name: "Chapter 88", updated_at: "45 phút trước" },
        ],
        genres: [{ id: "co-dai-207", name: "Cổ Đại" }, {}, {}, {}],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "0",
        updated_at: "44 phút trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://kcgsbok.com/nettruyen/thumb/shy.jpg",
        title: "SHY",
        id: "shy",
        is_trending: false,
        short_description:
          'Vào giữa thế kỷ 21, anh hùng có mặt khắp nơi trên khắp thế giới, nhưng trong số đó có một anh hùng siêu xấu hổ đến từ Nhật Bản với biệt danh là "Shy".Cô gánh trên mình trách nhiệm của một anh hùng, mặc dù bản thân rất kém trong việc đối mặt với ánh mắt từ mọi người.Dù gặp biết bao gian khó và khổ đau, nhưng Shy vẫn đứng lên vì những người xung quanh...!Mọi chuyện không chỉ dừng ở những cuộc xung đột, mà nó còn là câu chuyên về tình người, các anh hùng cùng mọi người hợp lực lại với nhau để tiến về phía trước!Câu chuyện trưởng thành về anh hùng mang tấm lòng nhân ái!',
        last_chapters: [
          { id: 74, name: "Chapter 74", updated_at: "44 phút trước" },
          { id: 73, name: "Chapter 73", updated_at: "2 ngày trước" },
          { id: 72, name: "Chapter 72", updated_at: "3 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "action-95", name: "Action" },
          { id: "sci-fi", name: "Sci-fi" },
          { id: "shounen-127", name: "Shounen" },
          { id: "drama-103", name: "Drama" },
          { id: "manga-112", name: "Manga" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 35K",
        total_comments: "8.42K",
        followers: "16.62K",
        updated_at: "44 phút trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/boss-cuoi-chap-nhan-tro-thanh-nguoi-choi.jpg",
        title: "Boss Cuối Chấp Nhận Trở Thành Người Chơi",
        id: "boss-cuoi-chap-nhan-tro-thanh-nguoi-choi",
        is_trending: true,
        short_description:
          "Trò chơi mới mở bị AI thần bí xâm chuyến, đại lục vốn là nơi phiêu lưu vui vẻ biến thành mê cung không cách nào thoát đi. Dưới ảnh hưởng của AL, ý thức của boss cuối đã thức tỉnh, thề phải bảo vệ trò chơi của mình, để nó khôi phục hình dạng nguyên bản",
        last_chapters: [
          { id: 22, name: "Chapter 22", updated_at: "51 phút trước" },
          { id: 21, name: "Chapter 21", updated_at: "51 phút trước" },
          { id: 20, name: "Chapter 20", updated_at: "1 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "fantasy-105", name: "Fantasy" },
          { id: "manhua", name: "Manhua" },
          { id: "mystery", name: "Mystery" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 1",
        total_comments: "0",
        followers: "11.47K",
        updated_at: "51 phút trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/cong-chua-be-con-hang-s-that-manh.jpg",
        title: "Công Chúa Bé Con Hạng S Thật Mạnh",
        id: "cong-chua-be-con-hang-s-that-manh",
        is_trending: false,
        short_description:
          "Truyện tranh Công Chúa Bé Con Hạng S Thật Mạnh được cập nhật sớm nhất và đầy đủ tại DocTruyen3Q. Bạn đọc đừng quên bình luận và chia sẻ, ủng hộ DocTruyen3Q ra các chương mới nhất của truyện Công Chúa Bé Con Hạng S Thật Mạnh.",
        last_chapters: [
          { id: 21, name: "Chapter 21", updated_at: "51 phút trước" },
          { id: 20, name: "Chapter 20", updated_at: "17 giờ trước" },
          { id: 19, name: "Chapter 19", updated_at: "1 ngày trước" },
        ],
        genres: [
          { id: "comedy-99", name: "Comedy" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "ngon-tinh", name: "Ngôn Tình" },
          { id: "romance-121", name: "Romance" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "260",
        updated_at: "51 phút trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://kcgsbok.com/nettruyen/thumb/tinh-vo-than-quyet.jpg",
        title: "Tinh Võ Thần Quyết",
        id: "tinh-vo-than-quyet",
        is_trending: true,
        short_description:
          "Quyền toái nhật nguyệt, chưởng thôn sơn hàĐạp nghịch thiên cường giả lộ, mỹ nhân làm bạn, tu luyện tinh võ truyền thừa, chấp chưởng quyền hành bát phương, thành tựu thần vương tối caoTừ thiếu nữ thiên tài ôn nhu, đáng yêu, quận chúa thân hình nóng bỏng tràn trề đến yêu tộc mỹ nữ thần bí, cao hơn nữa là nữ võ thần trong truyền thuyết tối cao...Một con đường ngộ đạo không tịch mịch, một truyền kỳ đầy sắc thái.",
        last_chapters: [
          { id: 712, name: "Chapter 715", updated_at: "52 phút trước" },
          { id: 711, name: "Chapter 714", updated_at: "52 phút trước" },
          { id: 710, name: "Chapter 713", updated_at: "1 ngày trước" },
        ],
        genres: [
          { id: "manhua", name: "Manhua" },
          { id: "mystery", name: "Mystery" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: ["Tinh Vũ Thần Quyết ", "星武神诀"],
        status: "Ongoing",
        total_views: " 13M",
        total_comments: "5.15M",
        followers: "2.23M",
        updated_at: "52 phút trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://kcgsbok.com/nettruyen/thumb/than-vo-thien-ton.jpg",
        title: "Thần Võ Thiên Tôn",
        id: "than-vo-thien-ton",
        is_trending: true,
        short_description:
          "Hái hoa Phi Diệp, có thể trảm nhật nguyệt sơn hà; Vừa nghĩ, bên trên hái cửu thiên tinh thần, hạ trấn lục đạo Hoàng Tuyền; Lật tay chưởng càn khôn, lật tay che thiên địa! Đây là... Thế giới của võ giả! Thiếu niên trùng sinh, đạp biến Chư Thiên Vạn Giới, chiến tận các tộc anh kiệt.",
        last_chapters: [
          { id: 704, name: "Chapter 714", updated_at: "53 phút trước" },
          { id: 703, name: "Chapter 713", updated_at: "3 ngày trước" },
          { id: 702, name: "Chapter 712", updated_at: "3 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhua", name: "Manhua" },
          { id: "mystery", name: "Mystery" },
          { id: "truyen-mau", name: "Truyện Màu" },
          { id: "xuyen-khong-205", name: "Xuyên Không" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 23K",
        total_comments: "774",
        followers: "64.49K",
        updated_at: "53 phút trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/song-sot-qua-ngay-tan-the.jpg",
        title: "Sống Sót Qua Ngày Tận Thế",
        id: "song-sot-qua-ngay-tan-the",
        is_trending: false,
        short_description:
          "Truyện tranh Sống Sót Qua Ngày Tận Thế được cập nhật sớm nhất và đầy đủ tại DocTruyen3Q. Bạn đọc đừng quên bình luận và chia sẻ, ủng hộ DocTruyen3Q ra các chương mới nhất của truyện Sống Sót Qua Ngày Tận Thế.",
        last_chapters: [
          { id: 25, name: "Chapter 25", updated_at: "53 phút trước" },
          { id: 24, name: "Chapter 24", updated_at: "6 ngày trước" },
          { id: 23, name: "Chapter 23", updated_at: "6 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "adventure", name: "Adventure" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 10",
        total_comments: "0",
        followers: "355",
        updated_at: "53 phút trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/chuyen-sinh-vao-the-gioi-vo-lam.jpg",
        title: "Chuyển Sinh Vào Thế Giới Võ Lâm",
        id: "chuyen-sinh-vao-the-gioi-vo-lam",
        is_trending: true,
        short_description:
          "Truyện tranh Chuyển Sinh Vào Thế Giới Võ Lâm được cập nhật nhanh và đầy đủ nhất tại TopTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ TopTruyen ra các chương mới nhất của truyện Chuyển Sinh Vào Thế Giới Võ Lâm.",
        last_chapters: [
          { id: 98, name: "Chapter 96", updated_at: "54 phút trước" },
          { id: 757080, name: "Chapter 95", updated_at: "3 tháng trước" },
          { id: 757079, name: "Chapter 94", updated_at: "3 tháng trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 7K",
        total_comments: "1.28K",
        followers: "69.91K",
        updated_at: "53 phút trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/ki-su-ba-nhat-the-gioi.jpg",
        title: "Kĩ Sư Bá Nhất Thế Giới",
        id: "ki-su-ba-nhat-the-gioi",
        is_trending: false,
        short_description:
          "Kim SooHo, một kỹ sư xây dựng, tỉnh dậy thì đã chuyển sinh thành một quý tộc trong cuốn tiểu thuyết đang đọc.Nói chung là hài =))",
        last_chapters: [
          { id: 161, name: "Chapter 161", updated_at: "54 phút trước" },
          { id: 160, name: "Chapter 160", updated_at: "6 ngày trước" },
          { id: 159, name: "Chapter 159", updated_at: "11 ngày trước" },
        ],
        genres: [
          { id: "chuyen-sinh-2130", name: "Chuyển Sinh" },
          { id: "comedy-99", name: "Comedy" },
          { id: "comic", name: "Comic" },
          { id: "drama-103", name: "Drama" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
          { id: "xuyen-khong-205", name: "Xuyên Không" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "1.02K",
        updated_at: "54 phút trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://ddntcthcd.com/nettruyen/thumb/trong-sinh-ma-tu.jpg",
        title: "Trọng Sinh Ma Tu",
        id: "trong-sinh-ma-tu",
        is_trending: false,
        short_description:
          "Sở Huyền xuyên không đến Thương Huyền thế giới, trở thành một ma tu của Vô Cực Tông. Cái gọi là tu ma, chính là hấp thu tinh hoa của trời đất, đoạt lấy tinh túy của vạn vật. Giết chóc hàng vạn sinh linh, mới có thể trở thành Đại Ma Tôn thông thiên. Tuy nhiên, việc giết chóc lại không được thiên đạo nhân tộc dung thứ. Vô Cực Tông cũng bị các tông môn chính đạo tiêu diệt. Trong lúc vô cùng tuyệt vọng, Sở Huyền tình cờ có được Huyết Kính, có thể đến một hành tinh tận thế đầy rẫy thây ma! Hắn kinh ngạc phát hiện, nơi này quả thật là một vùng đất phúc địa riêng biệt dành cho ma tu!",
        last_chapters: [
          { id: 7, name: "Chapter 7", updated_at: "1 giờ trước" },
          { id: 6, name: "Chapter 6", updated_at: "5 ngày trước" },
          { id: 5, name: "Chapter 5", updated_at: "11 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "fantasy-105", name: "Fantasy" },
          { id: "manhua", name: "Manhua" },
          { id: "psychological", name: "Psychological" },
          { id: "truyen-mau", name: "Truyện Màu" },
          { id: "xuyen-khong-205", name: "Xuyên Không" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "1.07K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/ta-co-90-ty-tien-liem-cau.jpg",
        title: "Ta Có 90 Tỷ Tiền Liếm Cẩu!",
        id: "ta-co-90-ty-tien-liem-cau",
        is_trending: true,
        short_description:
          "Sinh viên Trần Viễn crush nữ thần Lâm Thư Hình ba năm, lại bị đối phương một cước đạp bay. Sau khi đau khổ lại ngoài ý muốn kích hoạt hệ thống tiền liếm cẩu, còn có 90 tỷ tiền liếm cẩu, công dụng chỉ để simp nữ nhân! Càng xài nhiều tiền, càng thu được các loại thuộc tính. Tên là Liếm Cẩu Kim Hệ Thống thì ta thật sự cần liếm cẩu sao? Chỉ cần đủ nhiều tiền ta chính là trap boy chỉ cần dùng tiền là có thể chứng minh với nữ thần là ta đang liếm cẩu! Lúc này Trần Viễn đã mở ra con đường nhân sinh của mình!",
        last_chapters: [
          { id: 362, name: "Chapter 362", updated_at: "1 giờ trước" },
          { id: 361, name: "Chapter 361", updated_at: "23 giờ trước" },
          { id: 360, name: "Chapter 360", updated_at: "23 giờ trước" },
        ],
        genres: [
          { id: "drama-103", name: "Drama" },
          {},
          { id: "manhua", name: "Manhua" },
        ],
        other_names: "I Have 90 Billion Licking Gold Coins",
        status: "Ongoing",
        total_views: " 138K",
        total_comments: "0",
        followers: "82.39K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://kcgsbok.com/nettruyen/thumb/manh-nhat-di-gioi.jpg",
        title: "Mạnh Nhất Dị Giới",
        id: "manh-nhat-di-gioi",
        is_trending: true,
        short_description:
          "Truyện tranh Mạnh Nhất Dị Giới được cập nhật nhanh và đầy đủ nhất tại TopTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ TopTruyen ra các chương mới nhất của truyện Mạnh Nhất Dị Giới.",
        last_chapters: [
          { id: 31, name: "Chapter 30", updated_at: "1 giờ trước" },
          { id: 30, name: "Chapter 29", updated_at: "4 ngày trước" },
          { id: 29, name: "Chapter 28", updated_at: "7 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhua", name: "Manhua" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 12K",
        total_comments: "1.83K",
        followers: "16.67K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/nhat-niem-vinh-hang.jpg",
        title: "Nhất Niệm Vĩnh Hằng",
        id: "nhat-niem-vinh-hang",
        is_trending: true,
        short_description:
          "Nhất niệm thành biển cả, nhất niệm hóa nương dâu. Nhất niệm trảm nghìn Ma, nhất niệm giết vạn Tiên. Chỉ có niệm của ta... là Vĩnh hằng.",
        last_chapters: [
          { id: 122, name: "Chapter 90.5", updated_at: "1 giờ trước" },
          { id: 121, name: "Chapter 90", updated_at: "1 giờ trước" },
          { id: 120, name: "Chapter 89.5", updated_at: "1 ngày trước" },
        ],
        genres: [
          { id: "manhua", name: "Manhua" },
          { id: "adventure", name: "Adventure" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 110K",
        total_comments: "21.33K",
        followers: "32.2K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/ta-co-mot-son-trai.jpg",
        title: "Ta Có Một Sơn Trại",
        id: "ta-co-mot-son-trai",
        is_trending: true,
        short_description:
          "Truyện tranh Ta Có Một Sơn Trại được cập nhật nhanh và đầy đủ nhất tại DocTruyen3Q. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ DocTruyen3Q ra các chương mới nhất của truyện Ta Có Một Sơn Trại.",
        last_chapters: [
          { id: 1020, name: "Chapter 996", updated_at: "1 giờ trước" },
          { id: 1019, name: "Chapter 995", updated_at: "1 ngày trước" },
          { id: 1018, name: "Chapter 994", updated_at: "1 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "chuyen-sinh-2130", name: "Chuyển Sinh" },
          { id: "co-dai-207", name: "Cổ Đại" },
          { id: "fantasy-105", name: "Fantasy" },
          { id: "manhua", name: "Manhua" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "我有一座山寨",
        status: "Ongoing",
        total_views: " 130K",
        total_comments: "1.34K",
        followers: "11.22K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://kcgsbok.com/nettruyen/thumb/c-vi-thanh-than-3.jpg",
        title: "C Vị Thành Thần 3",
        id: "c-vi-thanh-than-3",
        is_trending: false,
        short_description:
          "Truyện tranh C Vị Thành Thần 3 được cập nhật sớm nhất và đầy đủ tại DocTruyen3Q. Bạn đọc đừng quên bình luận và chia sẻ, ủng hộ DocTruyen3Q ra các chương mới nhất của truyện C Vị Thành Thần 3.",
        last_chapters: [
          { id: 32, name: "Chapter 32", updated_at: "1 giờ trước" },
          { id: 31, name: "Chapter 31", updated_at: "6 ngày trước" },
          { id: 30, name: "Chapter 30", updated_at: "13 ngày trước" },
        ],
        genres: [{ id: "comedy-99", name: "Comedy" }, {}, {}],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "59",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/anh-hung-bi-truc-xuat.jpg",
        title: "Anh Hùng Bị Trục Xuất",
        id: "anh-hung-bi-truc-xuat",
        is_trending: false,
        short_description:
          "Truyện tranh Anh Hùng Bị Trục Xuất được cập nhật sớm nhất và đầy đủ tại DocTruyen3Q. Bạn đọc đừng quên bình luận và chia sẻ, ủng hộ DocTruyen3Q ra các chương mới nhất của truyện Anh Hùng Bị Trục Xuất.",
        last_chapters: [
          { id: 19, name: "Chapter 19", updated_at: "1 giờ trước" },
          { id: 18, name: "Chapter 18", updated_at: "14 ngày trước" },
          { id: 17, name: "Chapter 17", updated_at: "14 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "153",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/chien-binh-thon-phe-xac-chet.jpg",
        title: "Chiến Binh Thôn Phệ Xác Chết",
        id: "chien-binh-thon-phe-xac-chet",
        is_trending: true,
        short_description:
          "Truyện tranh Chiến Binh Thôn Phệ Xác Chết được cập nhật nhanh và đầy đủ nhất tại TopTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ TopTruyen ra các chương mới nhất của truyện Chiến Binh Thôn Phệ Xác Chết.",
        last_chapters: [
          { id: 47, name: "Chapter 47", updated_at: "1 giờ trước" },
          { id: 46, name: "Chapter 46", updated_at: "5 ngày trước" },
          { id: 45, name: "Chapter 45", updated_at: "10 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 204",
        total_comments: "0",
        followers: "16.43K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/sat-thu-thien-tai-don-doc.jpg",
        title: "Sát Thủ Thiên Tài Đơn Độc",
        id: "sat-thu-thien-tai-don-doc",
        is_trending: true,
        short_description:
          "Tôi xuyên không vào bộ tiểu thuyết mà tôi đã viết. Để thay đổi kết cục tận thế, tôi phải trở thành phản diện 'Shin Kanghu' và trở nên mạnh mẽ hơn cả anh hùng!",
        last_chapters: [
          { id: 49, name: "Chapter 48", updated_at: "1 giờ trước" },
          { id: 48, name: "Chapter 47", updated_at: "5 ngày trước" },
          { id: 47, name: "Chapter 46", updated_at: "13 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "fantasy-105", name: "Fantasy" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
          { id: "webtoon", name: "Webtoon" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 614",
        total_comments: "0",
        followers: "25.7K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/ban-dong-hanh-cua-ryun.jpg",
        title: "Bạn Đồng Hành Của Ryun",
        id: "ban-dong-hanh-cua-ryun",
        is_trending: false,
        short_description: "",
        last_chapters: [
          { id: 44, name: "Chapter 33", updated_at: "1 giờ trước" },
          { id: 43, name: "Chapter 32", updated_at: "1 giờ trước" },
          { id: 42, name: "Chapter 31", updated_at: "1 giờ trước" },
        ],
        genres: [{ id: "romance-121", name: "Romance" }],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "163",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/tsuyokute-new-game-na-love-come.jpg",
        title: "Tsuyokute New Game na Love Come",
        id: "tsuyokute-new-game-na-love-come",
        is_trending: false,
        short_description:
          "Main về cấp 1 cưa gái...Ủng hộ mình tại page: https://www.facebook.com/profile.php?id=61565890131689",
        last_chapters: [
          { id: 4, name: "Chapter 4", updated_at: "1 giờ trước" },
          { id: 3, name: "Chapter 3", updated_at: "1 ngày trước" },
          { id: 2, name: "Chapter 2", updated_at: "13 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "comedy-99", name: "Comedy" },
          { id: "romance-121", name: "Romance" },
          { id: "school-life", name: "School Life" },
          { id: "slice-of-life", name: "Slice of Life" },
          {},
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "28",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/cach-bao-ve-chu-nhan-cua-trang-vien-quai-vat.jpg",
        title: "Cách Bảo Vệ Chủ Nhân Của Trang Viên Quái Vật",
        id: "cach-bao-ve-chu-nhan-cua-trang-vien-quai-vat",
        is_trending: false,
        short_description:
          "Không! Thiếu gia được yêu mến đã chết một lần nữa! Khi thiếu gia của một trò chơi chết lần thứ 43, vòng thứ 44 bắt đầu, tiếp theo là một giọng nói lạ và một công việc, nhân vật và cốt truyện mới. Từ đó, trò chơi nuôi dạy con cái được Lynne yêu thích bắt đầu có một bước ngoặt kỳ lạ, trở nên giống một trò chơi hẹn hò hơn! Liệu cô ấy có thể cứu thiếu gia một lần nữa giữa những điều kỳ lạ này không?",
        last_chapters: [
          { id: 19, name: "Chapter 19", updated_at: "1 giờ trước" },
          { id: 18, name: "Chapter 18", updated_at: "1 giờ trước" },
          { id: 17, name: "Chapter 17", updated_at: "1 giờ trước" },
        ],
        genres: [{}, {}, {}],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "256",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://kcgsbok.com/nettruyen/thumb/chuoi-thuc-an.jpg",
        title: "Chuỗi Thức Ăn",
        id: "chuoi-thuc-an",
        is_trending: false,
        short_description:
          "Tôi, Go Eunwoo, đã sống ẩn giấu thân phận của mình giữa con người. Tôi đã dùng năng lực của mình để giảm bớt nỗi đau do bệnh ban đỏ, số phận của tộc Hổ mà tôi phải chịu đựng từ năm 18 tuổi nhưng lại bị kẻ thù truyền kiếp của tộc Tiger là Imae phát hiện. “Đừng ngu ngốc thế. Nếu bỏ chạy, bạn sẽ chết dưới tay tôi sau khoảng một tháng nữa ”.  Hơn nữa, Lee Mae lạnh lùng và đẹp trai đến đáng sợ này, Tôi không thể tin được mình có con dấu giống Lee Dohoon. Tôi câu giờ bằng cách nói dối, nhưng việc tôi bị bắt chỉ là vấn đề thời gian. Tôi phải thoát khỏi vòng tay của anh ấy bằng cách nào đó… ! “Xin hãy ở trong phòng với tôi trong thời gian này.” Tôi có thể quay lại cuộc sống thường nhật của mình được không?!",
        last_chapters: [
          { id: 288725, name: "Chapter 50", updated_at: "1 giờ trước" },
          { id: 288724, name: "Chapter 49", updated_at: "1 giờ trước" },
          { id: 288723, name: "Chapter 48", updated_at: "1 giờ trước" },
        ],
        genres: [{ id: "drama-103", name: "Drama" }, {}, {}, {}, {}, {}],
        other_names: "",
        status: "Ongoing",
        total_views: " 639",
        total_comments: "45",
        followers: "309",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/thang-than-tu-nghiem.jpg",
        title: "Thẳng Thắn Từ Nghiêm",
        id: "thang-than-tu-nghiem",
        is_trending: false,
        short_description:
          "Truyện tranh Thẳng Thắn Từ Nghiêm được cập nhật sớm nhất và đầy đủ tại DocTruyen3Q. Bạn đọc đừng quên bình luận và chia sẻ, ủng hộ DocTruyen3Q ra các chương mới nhất của truyện Thẳng Thắn Từ Nghiêm.",
        last_chapters: [
          { id: 125, name: "Chapter 127", updated_at: "1 giờ trước" },
          { id: 124, name: "Chapter 126", updated_at: "13 ngày trước" },
          { id: 123, name: "Chapter 125", updated_at: "20 ngày trước" },
        ],
        genres: [{}],
        other_names: "",
        status: "Ongoing",
        total_views: " 877K",
        total_comments: "102.12K",
        followers: "117.76K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/sieu-cap-than-co-nhan.jpg",
        title: "Siêu Cấp Thần Cơ Nhân",
        id: "sieu-cap-than-co-nhan",
        is_trending: true,
        short_description:
          "Trong tương lai, thời đại vũ trụ ầm ầm sóng dậy , nhân loại rốt cuộc có được kỹ thuật truyền tống trong không gian, thế nhưng sau khi con người truyện tống đến một chỗ khác thì lại phát hiện nơi đó cũng không phải là quá khứ hay tương lai, cũng không phải là bất cứ mảnh đất nào dưới trời sao. . . Một thế giới thần bí , có vô số dị sinh vật cường hoành , nhân loại nghênh đón kỷ nguyên tiến hóa làm người ta nhiệt huyết sôi trào, mở ra kỷ nguyên mới huy hoàng nhất dưới trời sao sáng chói .",
        last_chapters: [
          { id: 286, name: "Chapter 291", updated_at: "1 giờ trước" },
          { id: 285, name: "Chapter 290", updated_at: "5 ngày trước" },
          { id: 284, name: "Chapter 289", updated_at: "6 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhua", name: "Manhua" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: [
          "Siêu Cấp Thần Cơ Nhân",
          "Siêu Cấp Gen Thần",
          "Siêu Cấp Thần Gen",
        ],
        status: "Ongoing",
        total_views: " 1M",
        total_comments: "679.95K",
        followers: "207.84K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/toan-cau-bang-phong-ta-che-tao-phong-an-toan-tai-tan-the.jpg",
        title: "Toàn Cầu Băng Phong: Ta Chế Tạo Phòng An Toàn Tại Tận Thế",
        id: "toan-cau-bang-phong-ta-che-tao-phong-an-toan-tai-tan-the",
        is_trending: false,
        short_description:
          "Toàn cầu tiến vào thời đại băng hà, 95% nhân loại mất mạng! Ở kiếp trước, Trương Dịch lòng dạ lương thiện, nhưng kết quả lại bị người ta lấy ân báo oán. Kiếp này, Trương Dịch trùng sinh trở về, thức tỉnh không gian dị năng, điên cuồng lưu trữ vật tư! Hàn băng tận thế, phân đất vi vương! Thề phải hoàn trả lại quá khứ đau khổ gấp cả trăm lần!",
        last_chapters: [
          { id: 454, name: "Chapter 453", updated_at: "1 giờ trước" },
          { id: 453, name: "Chapter 452", updated_at: "1 ngày trước" },
          { id: 452, name: "Chapter 451", updated_at: "3 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "chuyen-sinh-2130", name: "Chuyển Sinh" },
          { id: "drama-103", name: "Drama" },
          { id: "manhua", name: "Manhua" },
          { id: "supernatural", name: "Supernatural" },
          { id: "truyen-mau", name: "Truyện Màu" },
          { id: "horror", name: "Horror" },
        ],
        other_names: [
          "Trái Đất Đóng Băng: Tôi Gầy Dựng Nên Phòng An Toàn Thời Tận Thế",
          "Sông Băng Tận Thế",
          " Ta Trữ Hàng Chục Tỷ Vật Tư",
        ],
        status: "Ongoing",
        total_views: " 445K",
        total_comments: "134.11K",
        followers: "178.59K",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/xich-chat-ong-chu-cua-toi.jpg",
        title: "Xích Chặt Ông Chủ Của Tôi",
        id: "xich-chat-ong-chu-cua-toi",
        is_trending: false,
        short_description: "",
        last_chapters: [
          { id: 36, name: "Chapter 36", updated_at: "1 giờ trước" },
          { id: 35, name: "Chapter 35", updated_at: "1 giờ trước" },
          { id: 34, name: "Chapter 34", updated_at: "1 giờ trước" },
        ],
        genres: [{ id: "romance-121", name: "Romance" }],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "173",
        updated_at: "1 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/danshi-kokoseidakedo-gyaru-ni-ts-shimashita.jpg",
        title: "Danshi Kokoseidakedo Gyaru ni TS Shimashita",
        id: "danshi-kokoseidakedo-gyaru-ni-ts-shimashita",
        is_trending: false,
        short_description:
          "À thì một thanh niên trầm tính vô tình cứu một nữ thần gyaru và được trả ơn bằng cuộc sống mới",
        last_chapters: [
          { id: 4, name: "Chapter 4", updated_at: "2 giờ trước" },
          { id: 3, name: "Chapter 3", updated_at: "2 giờ trước" },
          { id: 2, name: "Chapter 2", updated_at: "2 giờ trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "comedy-99", name: "Comedy" },
          { id: "school-life", name: "School Life" },
          { id: "slice-of-life", name: "Slice of Life" },
          { id: "gender-bender", name: "Gender Bender" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "0",
        updated_at: "2 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/ngu-tri-ta-vi-chua-tan-bao-zankoku-na-kami-ga-shihaisuru.jpg",
        title: "Ngự Trị Ta, Vị Chúa Tàn Bạo - Zankoku Na Kami Ga Shihaisuru",
        id: "ngu-tri-ta-vi-chua-tan-bao-zankoku-na-kami-ga-shihaisuru",
        is_trending: false,
        short_description:
          'Sự hy sinh điên rồ đã kéo cậu bé Jeremy xuống vực thẳm, lang thang vô định và đánh mất tiếng nói. Liệu rằng Jeremy có bao giờ trở về được thế giới loài người? Đến với "Ngự trị ta, vị chúa tàn bạo  Zankokuna Kami Ga Shihaisuru" để cùng Jeremy và những người cậu yêu thương thoát khỏi khu rừng hỗn độn giữa tình yêu và bạo lực, tìm ra con đường giữa lằn ranh sinh tử. Sau cùng, liệu con người có thể thoát khỏi vị chúa tàn bạo vẫn hằng ngự trị chúng ta? Hy vọng bạn sẽ theo dõi đến cùng và tìm được câu trả lời cho riêng mình.',
        last_chapters: [
          { id: 51, name: "Chapter 51", updated_at: "3 giờ trước" },
          { id: 50, name: "Chapter 50", updated_at: "16 ngày trước" },
          { id: 49, name: "Chapter 49", updated_at: "16 ngày trước" },
        ],
        genres: [
          { id: "drama-103", name: "Drama" },
          { id: "manga-112", name: "Manga" },
          { id: "psychological", name: "Psychological" },
          { id: "romance-121", name: "Romance" },
          { id: "school-life", name: "School Life" },
          { id: "tragedy-136", name: "Tragedy" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 389",
        total_comments: "0",
        followers: "28",
        updated_at: "3 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/tu-phu-thuy-manh-nhat-khu-o-chuot-den-vo-song-tai-hoc-vien-phap-thuat-hoang-gia.jpg",
        title:
          "Từ Phù Thủy Mạnh Nhất Khu Ổ Chuột Đến Vô Song Tại Học Viện Pháp Thuật Hoàng Gia",
        id: "tu-phu-thuy-manh-nhat-khu-o-chuot-den-vo-song-tai-hoc-vien-phap-thuat-hoang-gia",
        is_trending: false,
        short_description:
          'Áp đảo giới quý tộc, pháp sư mạnh nhất từ ​​khu ổ chuột !! Ars vốn là một thằng ăn cắp vặt trong khu ổ chuột. Và được nhận nuôi để trở thành sát thủ. Ở tuổi 15, Ars được khuyên nên đi học để đủ tiêu chuẩn trở thành "Pháp sư". Vừa bước vào cổng trường, là sự xuất hiện của những quý tộc có trình độ không bằng một cái móng tay của Ars, người đã vượt qua kỳ kiểm tra đầu vào với khả năng vượt trội, bắt đầu một cuộc sống khác thường .Là học sinh vào ban ngày và một sát thủ vào ban đêm !!',
        last_chapters: [
          { id: 720864, name: "Chapter 102", updated_at: "3 giờ trước" },
          { id: 102, name: "Chapter 100", updated_at: "9 ngày trước" },
          { id: 101, name: "Chapter 99", updated_at: "9 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "drama-103", name: "Drama" },
          { id: "fantasy-105", name: "Fantasy" },
          { id: "manga-112", name: "Manga" },
          { id: "mystery", name: "Mystery" },
          { id: "school-life", name: "School Life" },
          { id: "shounen-127", name: "Shounen" },
        ],
        other_names:
          "The Irregular of the Royal Academy of Magic ~The Strongest Sorcerer From the Slums is Unrivaled in the School of Royals ~",
        status: "Ongoing",
        total_views: " 14K",
        total_comments: "2.03K",
        followers: "2.24K",
        updated_at: "3 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/tai-khoan-bi-mat-cua-vo-yeu.jpg",
        title: "Tài Khoản Bí Mật Của Vợ Yêu",
        id: "tai-khoan-bi-mat-cua-vo-yeu",
        is_trending: false,
        short_description:
          "Yamada Sosuke, người có một cô con gái đang học tiểu học, tình cờ xem được đoạn video ghi lại cảnh người có vẻ là vợ anh đang quan hệ tình dục trong một tài khoản nặc danh. Hơn nữa, đoạn video còn được quay tại trường tiểu học mà con gái anh đang theo học. Chủ tài khoản bí mật có thực sự là vợ anh không? Và cô ấy đang ngoại tình với ai?",
        last_chapters: [
          { id: 8, name: "Chapter 8", updated_at: "3 giờ trước" },
          { id: 7, name: "Chapter 7", updated_at: "3 giờ trước" },
          { id: 6, name: "Chapter 6", updated_at: "3 giờ trước" },
        ],
        genres: [
          { id: "manga-112", name: "Manga" },
          { id: "psychological", name: "Psychological" },
          {},
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "84",
        updated_at: "3 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/unmei-no-makimodoshi.jpg",
        title: "Unmei No Makimodoshi",
        id: "unmei-no-makimodoshi",
        is_trending: false,
        short_description:
          'Biệt đội cơ động cảnh sát thời không, hay còn gọi tắt là "Cảnh sát thời gian" (Người tua ngược/Rewinder) là một tổ chức giải cứu những người có cái chết bất đắc kì tử! Họ sử dụng một cỗ máy thời gian ở mắt phải "Retry Eye"! Những cảnh sát thời gian có thể quay ngược thời gian hàng chục, hàng trăm tới hàng nghìn lần cho đến khi phá được vụ án! Bộ truyện từng lập kỷ lục suốt 1 năm liền đứng đầu liên tục trong danh sát truyện yêu thích của tạp chí Corocoro Comic.',
        last_chapters: [
          { id: 31, name: "Chapter 27", updated_at: "3 giờ trước" },
          { id: 30, name: "Chapter 26.5", updated_at: "4 ngày trước" },
          { id: 29, name: "Chapter 26", updated_at: "7 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "action-95", name: "Action" },
          { id: "shounen-127", name: "Shounen" },
          { id: "supernatural", name: "Supernatural" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "54",
        updated_at: "3 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/phong-thu-ham-nguc.jpg",
        title: "Phòng Thủ Hầm Ngục",
        id: "phong-thu-ham-nguc",
        is_trending: true,
        short_description:
          "Truyện tranh Phòng Thủ Hầm Ngục được cập nhật nhanh và đầy đủ nhất tại TopTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ TopTruyen ra các chương mới nhất của truyện Phòng Thủ Hầm Ngục.",
        last_chapters: [
          { id: 35, name: "Chapter 34", updated_at: "4 giờ trước" },
          { id: 34, name: "Chapter 33", updated_at: "6 ngày trước" },
          { id: 33, name: "Chapter 32", updated_at: "7 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 4",
        total_comments: "0",
        followers: "18.8K",
        updated_at: "4 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/bien-nien-su-cua-thien-quy.jpg",
        title: "Biên Niên Sử Của Thiên Quỷ",
        id: "bien-nien-su-cua-thien-quy",
        is_trending: true,
        short_description:
          "Chính đạo là bọn khốn, đã hãm hại sư phụ ta, ta trùng sinh gia nhập quỷ đạo trả mối huyết thù",
        last_chapters: [
          { id: 239, name: "Chapter 239", updated_at: "4 giờ trước" },
          { id: 757741, name: "Chapter 238", updated_at: "13 ngày trước" },
          { id: 757740, name: "Chapter 237", updated_at: "13 ngày trước" },
        ],
        genres: [
          { id: "adventure", name: "Adventure" },
          { id: "chuyen-sinh-2130", name: "Chuyển Sinh" },
          { id: "manhua", name: "Manhua" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 851",
        total_comments: "78",
        followers: "27.74K",
        updated_at: "4 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/dao-ma-ca-rong-phan-3.jpg",
        title: "Đảo Ma Cà Rồng Phần 3",
        id: "dao-ma-ca-rong-phan-3",
        is_trending: false,
        short_description:
          "Truyện này kể về 1 hòn đảo gồm những con ma cà rồng phải oằn mình chống lại 1 con quái vật đến từ thế giới bên ngoài có tên là Akira để có thể bảo tồn giống nòi ma cà rồng của mình Thanh niên Vampire Miyabi sau khi thoát khỏi thí nghiệm tàn khốc của chính phủ,sự giam cầm vô nhân đạo của loài người đã tập hợp lực lượng để bảo vệ chủng tộc Vampire thoát khỏi cảnh diệt chủng,đáng tiếc công cuộc này thường xuyên bị những phần tử xấu xa mà nổi bật nhất là Akira ngăn cản,biết bao nhiêu đồng loại Vampire đã ngã xuống dưới lưỡi kiếm tàn nhẫn của Akira nhưng Miyabi vẫn không nản lòng,vẫn mong Akira có thể thấu hiểu mình như Thần Rìu đã thấu hiểu và sát cánh bên anh. Phần 1 + Phần 2",
        last_chapters: [
          { id: 377, name: "Chapter 876", updated_at: "4 giờ trước" },
          { id: 376, name: "Chapter 875", updated_at: "4 giờ trước" },
          { id: 375, name: "Chapter 874", updated_at: "4 ngày trước" },
        ],
        genres: [
          { id: "fantasy-105", name: "Fantasy" },
          { id: "manga-112", name: "Manga" },
          { id: "mystery", name: "Mystery" },
          { id: "horror", name: "Horror" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 2M",
        total_comments: "303",
        followers: "2.53K",
        updated_at: "4 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://kcgsbok.com/nettruyen/thumb/tinh-lai-di-jeon-seung-yeon.jpg",
        title: "Tỉnh Lại Đi, Jeon Seung Yeon!",
        id: "tinh-lai-di-jeon-seung-yeon",
        is_trending: false,
        short_description:
          "Seung Yeon nổi tiếng nhờ khuôn mặt xinh xắn, chiều cao cao và khí chất độc đáo, làm việc bán thời gian tại quán net và thường bị những khách hàng nam ưu ái cô đánh giá thấp lòng tự trọng. Bây giờ đang học năm thứ tư, Seung Yeon biết rằng mình phải tập trung vào việc học, nhưng cô không thể dễ dàng bỏ công việc bán thời gian ở quán net, vì vậy cô đã gặp Lee Beom rất hấp dẫn…",
        last_chapters: [
          { id: 1, name: "Chapter 1", updated_at: "4 giờ trước" },
        ],
        genres: [
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "romance-121", name: "Romance" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "0",
        updated_at: "4 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/thiet-huyet-kiem-si-hoi-quy.jpg",
        title: "Thiết Huyết Kiếm Sĩ Hồi Quy",
        id: "thiet-huyet-kiem-si-hoi-quy",
        is_trending: true,
        short_description:
          "1 tác phẩm đến từ Red Ice Studio, studio đã thực hiện Tử Thần Phiêu Nguyệt, Thợ Rèn Huyền Thoại, Cửu Thiên Cực Kiếm...",
        last_chapters: [
          { id: 79, name: "Chapter 79", updated_at: "4 giờ trước" },
          { id: 78, name: "Chapter 78", updated_at: "7 ngày trước" },
          { id: 77, name: "Chapter 77", updated_at: "7 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "Thiết Huyết Cẩu Kiếm Sĩ Báo Thù",
        status: "Ongoing",
        total_views: " 27K",
        total_comments: "5.7K",
        followers: "130.13K",
        updated_at: "4 giờ trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/hau-cung-cua-nu-de-mua-2.jpg",
        title: "Hậu Cung Của Nữ Đế - Mùa 2",
        id: "hau-cung-cua-nu-de-mua-2",
        is_trending: false,
        short_description: "",
        last_chapters: [
          { id: 89, name: "Chapter 90", updated_at: "44 phút trước" },
          { id: 88, name: "Chapter 89", updated_at: "44 phút trước" },
          { id: 87, name: "Chapter 88", updated_at: "45 phút trước" },
        ],
        genres: [{ id: "co-dai-207", name: "Cổ Đại" }, {}, {}, {}],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "0",
        updated_at: "44 phút trước",
        authors: "Updating",
      },
      {
        thumbnail: "https://kcgsbok.com/nettruyen/thumb/shy.jpg",
        title: "SHY",
        id: "shy",
        is_trending: false,
        short_description:
          'Vào giữa thế kỷ 21, anh hùng có mặt khắp nơi trên khắp thế giới, nhưng trong số đó có một anh hùng siêu xấu hổ đến từ Nhật Bản với biệt danh là "Shy".Cô gánh trên mình trách nhiệm của một anh hùng, mặc dù bản thân rất kém trong việc đối mặt với ánh mắt từ mọi người.Dù gặp biết bao gian khó và khổ đau, nhưng Shy vẫn đứng lên vì những người xung quanh...!Mọi chuyện không chỉ dừng ở những cuộc xung đột, mà nó còn là câu chuyên về tình người, các anh hùng cùng mọi người hợp lực lại với nhau để tiến về phía trước!Câu chuyện trưởng thành về anh hùng mang tấm lòng nhân ái!',
        last_chapters: [
          { id: 74, name: "Chapter 74", updated_at: "44 phút trước" },
          { id: 73, name: "Chapter 73", updated_at: "2 ngày trước" },
          { id: 72, name: "Chapter 72", updated_at: "3 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "action-95", name: "Action" },
          { id: "sci-fi", name: "Sci-fi" },
          { id: "shounen-127", name: "Shounen" },
          { id: "drama-103", name: "Drama" },
          { id: "manga-112", name: "Manga" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 35K",
        total_comments: "8.42K",
        followers: "16.62K",
        updated_at: "44 phút trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/boss-cuoi-chap-nhan-tro-thanh-nguoi-choi.jpg",
        title: "Boss Cuối Chấp Nhận Trở Thành Người Chơi",
        id: "boss-cuoi-chap-nhan-tro-thanh-nguoi-choi",
        is_trending: true,
        short_description:
          "Trò chơi mới mở bị AI thần bí xâm chuyến, đại lục vốn là nơi phiêu lưu vui vẻ biến thành mê cung không cách nào thoát đi. Dưới ảnh hưởng của AL, ý thức của boss cuối đã thức tỉnh, thề phải bảo vệ trò chơi của mình, để nó khôi phục hình dạng nguyên bản",
        last_chapters: [
          { id: 22, name: "Chapter 22", updated_at: "51 phút trước" },
          { id: 21, name: "Chapter 21", updated_at: "51 phút trước" },
          { id: 20, name: "Chapter 20", updated_at: "1 ngày trước" },
        ],
        genres: [
          { id: "action-95", name: "Action" },
          { id: "fantasy-105", name: "Fantasy" },
          { id: "manhua", name: "Manhua" },
          { id: "mystery", name: "Mystery" },
          { id: "truyen-mau", name: "Truyện Màu" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 1",
        total_comments: "0",
        followers: "11.47K",
        updated_at: "51 phút trước",
        authors: "Updating",
      },
      {
        thumbnail:
          "https://ddntcthcd.com/nettruyen/thumb/cong-chua-be-con-hang-s-that-manh.jpg",
        title: "Công Chúa Bé Con Hạng S Thật Mạnh",
        id: "cong-chua-be-con-hang-s-that-manh",
        is_trending: false,
        short_description:
          "Truyện tranh Công Chúa Bé Con Hạng S Thật Mạnh được cập nhật sớm nhất và đầy đủ tại DocTruyen3Q. Bạn đọc đừng quên bình luận và chia sẻ, ủng hộ DocTruyen3Q ra các chương mới nhất của truyện Công Chúa Bé Con Hạng S Thật Mạnh.",
        last_chapters: [
          { id: 21, name: "Chapter 21", updated_at: "51 phút trước" },
          { id: 20, name: "Chapter 20", updated_at: "17 giờ trước" },
          { id: 19, name: "Chapter 19", updated_at: "1 ngày trước" },
        ],
        genres: [
          { id: "comedy-99", name: "Comedy" },
          { id: "manhwa-11400", name: "Manhwa" },
          { id: "ngon-tinh", name: "Ngôn Tình" },
          { id: "romance-121", name: "Romance" },
        ],
        other_names: "",
        status: "Ongoing",
        total_views: " 0",
        total_comments: "0",
        followers: "260",
        updated_at: "51 phút trước",
        authors: "Updating",
      },
    ],
    total_pages: 2,
    current_page: 1,
  },
};

export default CONSTANTS;
